### ISSUE TITLE
Django 3.1.4 - cannot import python_2_unicode_compatible

### ISSUE THREAD

**Issue by rdandy** [frankovo/django-random-id-generator#1]
import error installing with django 3.1.4: [django removed](https://docs.djangoproject.com/en/3.0/releases/3.0/)

`ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'`

I found the same issue here: [https://github.com/pinax/pinax-blog/issues/128](https://github.com/pinax/pinax-blog/issues/128)

The solution is..
replace: `from django.utils.encoding import python_2_unicode_compatible`
with: `from six import python_2_unicode_compatible`

FYI

**Comment by frankovo** [comment]
I will make the update as soon as possible. Thanks @rdandy

**Comment by frankovo** [comment]
Fixed thanks again @rdandy
